# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\" \n\rUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\x1a\n\x0c\x42oolResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xac\x01\n\x08UserFull\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x06 \x01(\t\x12\x17\n\x0fpassport_number\x18\x07 \x01(\t\x12\x12\n\nbirth_date\x18\x08 \x01(\t\x12\x0e\n\x06tax_id\x18\t \x01(\t2\xac\x01\n\x0bUserService\x12\x30\n\x07GetUser\x12\x14.users.UserIdRequest\x1a\x0f.users.UserFull\x12\x34\n\x07\x42\x61nUser\x12\x14.users.UserIdRequest\x1a\x13.users.BoolResponse\x12\x35\n\x08IsBanned\x12\x14.users.UserIdRequest\x1a\x13.users.BoolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERIDREQUEST']._serialized_start=22
  _globals['_USERIDREQUEST']._serialized_end=54
  _globals['_BOOLRESPONSE']._serialized_start=56
  _globals['_BOOLRESPONSE']._serialized_end=82
  _globals['_USERFULL']._serialized_start=85
  _globals['_USERFULL']._serialized_end=257
  _globals['_USERSERVICE']._serialized_start=260
  _globals['_USERSERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
