name: CI/CD Deploy

# Триггер — пуш в ветку main (или master, если у тебя она так названа)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Настраиваем SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # 3) Деплой первого сервиса
      - name: Deploy service1
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /home/${{ secrets.DEPLOY_USER }}/projects/repo/service1
            git pull origin main
            # если используешь docker-compose:
            docker-compose down
            docker-compose up -d --build
          EOF

      # 4) Деплой второго сервиса
      - name: Deploy service2
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd /home/${{ secrets.DEPLOY_USER }}/projects/repo/service2
            git pull origin main
            # если сервис — просто образ Docker:
            docker build -t service2 .
            docker rm -f service2 || true
            docker run -d --name service2 -p 8001:8000 service2
          EOF